STACKSIZE		= 64k
OPTIMISATION		= -O2 -fomit-frame-pointer -finline-functions
CPU			= -m68020-60
LIB			= -lshare -lldg

CFLAGS			= $(CPU) $(OPTIMISATION) -Wall -I../../../common -I../common

OBJ 			= godldg.o

PROGRAM 		= godpaint.ldg

include ../../../common.mak
