STACKSIZE		= 64k
OPTIMISATION		= -O2 -fomit-frame-pointer
CPU			= -m68020-60
LIB			= -lldg -lpng -lm -lz

CFLAGS			= $(CPU) $(OPTIMISATION) -Wall -I../common

OBJ			= pngldg.o

PROGRAM 		= png.ldg

include ../../../common.mak
