STACKSIZE		= 4k
OPTIMISATION		= -O3 -fomit-frame-pointer -finline-functions
CPU			= -m68020-60
LIB			= -lshare -lldg

CFLAGS			= $(CPU) $(OPTIMISATION) -Wall

OBJ 			= neoldg.o

PROGRAM 		= neo.ldg

include ../../../common.mak
