default:
	make -C src clean CPU="" PROGRAM="../lib/libzcodec.a"
	make -C src CPU="" PROGRAM="../lib/libzcodec.a"

	make -C src clean CPU="-m68020-60" PROGRAM="../lib/m68020-60/libzcodec.a"
	make -C src CPU="-m68020-60" PROGRAM="../lib/m68020-60/libzcodec.a"

	make -C src clean CPU="-mcpu=5475" PROGRAM="../lib/m5475/libzcodec.a"
	make -C src CPU="-mcpu=5475" PROGRAM="../lib/m5475/libzcodec.a"
