STACKSIZE		= 8k
OPTIMISATION		= -O2 -fomit-frame-pointer -finline-functions
CPU			= -m68020-60
LIB			= -lshare -lldg

CFLAGS			= $(CPU) $(OPTIMISATION) -Wall

OBJ 			= imgldg.o xp32.o

PROGRAM 		= img.ldg

include ../../../common.mak
