STACKSIZE		= 64k
OPTIMISATION		= -O2 -fomit-frame-pointer -finline-functions
CPU			= -m68020-60
LIB			= -lldg

CFLAGS			= $(CPU) $(OPTIMISATION) -Wall -I../common

OBJ 			= imgldg.o xp32.o

PROGRAM 		= img.ldg

include ../../../common.mak
