STACKSIZE		= 4k
OPTIMISATION		= -O2 -fomit-frame-pointer -finline-functions
CPU			= -m68020-60
LIB			= -lldg

CFLAGS			= $(CPU) $(OPTIMISATION) -Wall -I../common

OBJ 			= rawldg.o

PROGRAM 		= eureka.ldg

include ../../../common.mak
