STACKSIZE		= 4k
OPTIMISATION		= -O3 -fomit-frame-pointer -finline-functions
CPU			= -m68020-60
LIB			= -lldg

CFLAGS			= $(CPU) $(OPTIMISATION) -Wall -I../common

OBJ 			= godldg.o

PROGRAM 		= godpaint.ldg

include ../../../common.mak
